### ISSUE TITLE
Try to read SUPERBLOCK and inode tables before formatting them on the disk

### ISSUE THREAD

**Issue by reaganmcf** [reaganmcf/tiny-file-system#7]
Right now we assume we build superblock every time and rewrite the inode table instead of attempting to load it into the structs first.

**Comment by evanwire** [comment]
I attempted to fix this issue, however I was not successful. I added a condition that reads block 0 into SUPERBLOCK, and if the magic number is wrong, it would create new superblock and bitmaps. If the magic_num was the correct one, it should read the bitmaps. However, this doesn't make any difference. I think that resolving this issue will have something to do with dev_open, dev_init, and dev_close.

**Comment by reaganmcf** [comment]
This was fixed in 0a6ffa63a8961939578584ee2cfb1f8e3df19651
