### ISSUE TITLE
When inside an embedded folder, doing "cd .." does not take you back to the parent directory

### ISSUE THREAD

**Issue by evanwire** [reaganmcf/tiny-file-system#9]

**Comment by evanwire** [comment]
I think this is an issue with dir_add but I'm not sure where

**Comment by reaganmcf** [comment]
Im actually unable to reproduce this.

![](https://i.gyazo.com/f974cfcb110f2dd65e6f66bf5b6ee115.png)

**Comment by evanwire** [comment]
Seems to be working now: assuming its cus i didnt replace my DISKFILE for some time
